= Gitea Operator

== Overview

This repository contains the code to build a Gitea Operator for Red Hat OpenShift Container Platform. It will not run on Kubernetes because it uses the `Route` object to provide access to Gitea.

The Operator will create a *PostgreSQL* database with persistent storage and a *Gitea Server* also with persistent storage connected to the PostgreSQL database.

It is implemented on top of the Red Hat https://github.com/operator-framework/operator-sdk[Operator SDK] - in particular the https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md[Ansible Operator].

== Building the Operator

There is a script `build.sh` which will download the prerequisite Ansible roles from https://github.com/redhat-gpte-devopsautomation/ansible-operator-roles and install the required roles. The script will then build the container image.

Before running the script make sure to update the location of the container image to a repository you have access to. If you decide to build your own also make sure to update deploy/operator.yaml with the updated container image location.

== Installation

Perform the following tasks as *cluster-admin*:

. Deploy the Custom Resource Definition:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/crds/gpte_v1alpha1_gitea_crd.yaml
----

. Create the Cluster Role for the Operator
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/cluster_role.yaml
----

. Create a project for the operator to run in (different from where the application will be running)
+
[source,sh]
----
oc new-project gpte-operators --display-name="GPTE Operators"
----

. Deploy the *gitea-operator* service account (replace the project name with your project name):
+
[source,sh]
----
oc create sa gitea-operator -n gpte-operators
----

. Grant the *gitea-operator* role to the *gitea-operator* service account (if your project is not `gpte-operators` change the project name in the command):
+
[source,sh]
----
oc adm policy add-cluster-role-to-user gitea-operator system:serviceaccount:gpte-operators:gitea-operator
----

. And finally create the Gitea *Operator*:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/operator.yaml -n gpte-operators
----

. Once the Operator pod is running the Operator is ready to start creating Gitea Servers.

== Deploying a Gitea Server using the Operator

The Gitea Server is deployed by creating a Custom Resource based on the gitea Custom Resource Definition. There is an example of a Gitea CR at https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/crds/gpte_v1alpha1_gitea_cr.yaml.

The Gitea Operator understands the following settings under it's *spec* setting:

* postgresqlVolumeSize: The size of the Persistent Volume to be created for the PostgreSQL database (e.g. 4Gi)
* giteaVolumeSize: The size of the Persistent Volume to be created for the Gitea database (e.g. 4Gi)
* giteaSsl: Weather the created route should be a HTTP (false) or HTTPS (true) route.
* giteaServiceName: Optional. The name of the gitea service. The default is "metadata.name" where _metadata.name_ is the name of the CR object (in the example below `gitea-server`). When specifying this parameter ensure that the service name does not already exist in the project/namespace.
* giteaRoute: The fully qualified route of the Gitea route to be created. This route must be reachable via ingress controllers.

.Example
[source,texinfo]
----
apiVersion: gpte.opentlc.com/v1alpha1
kind: Gitea
metadata:
  name: gitea-server
spec:
  postgresqlVolumeSize: 4Gi
  giteaVolumeSize: 4Gi
  giteaSsl: True
  giteaServiceName: mygitea
----

. Write the definition to a file (e.g. gitea-server.yaml) and then create the Gitea instance:
+
[source,sh]
----
oc create -f ./gitea-server.yaml
----

. The operator will first create the PostgreSQL database, wait until it is up and running and then create the Gitea Server.
. Validate that both pods (postgresql and gitea) are running before proceeding.
. You can validate the existence of your Gitea Server by querying for gitea objects:
+
[source,sh]
----
oc get gitea
----

. Get the Route for the Gitea Server (the PostgreSQL database is not accessible outside of the project):
+
[source,sh]
----
oc get route
----

. Use the hostname returned in your Web Browser to open the Gitea UI.

== Deleting a Gitea Server

Deleting a gitea server and its associated resources is as simple as deleting the gitea object. If you created a gitea server called `gitea-server` as in the example above it suffices to run the delete command on that resource:

[source,sh]
----
oc delete gitea gitea-server
----

The Operator adds ownerReference fields to all created objects - which means that deleting the Gitea object also deletes all objects that have been created by the Operator.

== Uninstalling the Gitea Operator

In case you wish to uninstall the Gitea Operator make sure that there are no more Gitea instances running. Once all Gitea instances have been deleted simply delete the project the operator is running in.

[source,sh]
----
oc delete project gpte-operators
----

Then as *cluster-admin* delete the ClusterRole and Custom Resource:

[source,sh]
----
oc delete clusterrole gitea-operator
oc delete crd gitea.gpte.opentlc.com
----
