= Gitea Operator

== Overview

This repository contains the code to build a Gitea Operator for Red Hat OpenShift Container Platform. It will not run on Kubernetes because it uses the `Route` object to provide access to Gitea.

The Operator will create a *PostgreSQL* database with persistent storage and a *Gitea Server* also with persistent storage connected to the PostgreSQL database.

It is implemented on top of the Red Hat https://github.com/operator-framework/operator-sdk[Operator SDK] - in particular the https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md[Ansible Operator].

== Building the Operator

There is a script `build.sh` which will download the prerequisite Ansible roles from https://github.com/redhat-gpte-devopsautomation/ansible-operator-roles and install the required roles. The script will then build the container image.

Before running the script make sure to update the location of the container image to a repository you have access to. If you decide to build your own also make sure to update deploy/operator.yaml with the updated container image location.

== Installation

The installation of the Custom Resource Definition and Cluster Role requires *cluster-admin* privileges. After that regular users with `admin` privileges on their projects (which is automatically granted to the user who creates a project) can provision the Gitea Operator in their projects and deploy instances of Gitea using the gitea.gpte.opentlc.com Custom Resource.

=== Cluster-Admin Tasks

Perform the following tasks as *cluster-admin*:

. Deploy the Custom Resource Definition:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/crds/gitea_v1alpha1_gitea_crd.yaml
----

. Deploy the `gitea-admin-rules` Cluster Role (which will be granted automatically to everyone with `admin` privileges):
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/clusterrole.yaml
----

=== Regular User Tasks

The next steps work either as *cluster-admin* or as a *regular user*.

. Create a new project in which to deploy Gitea:
+
[source,sh]
----
oc new-project gitea --display-name "Gitea Server"
----

. Deploy the *gitea-operator* service account:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/service_account.yaml
----

. Deploy the *gitea-operator* role:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/role.yaml
----

. Grant the *gitea-operator* role to the *gitea-operator* service account:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/role_binding.yaml
----

. And finally create the Gitea *Operator*:
+
[source,sh]
----
oc create -f https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/operator.yaml
----

. Once the Operator pod is running the Operator is ready to start creating Gitea Servers.

== Deploying a Gitea Server using the Operator

The Gitea Server is deployed by creating a Custom Resource based on the gitea Custom Resource Definition. There is an example of a Gitea CR at https://raw.githubusercontent.com/wkulhanek/gitea-operator/master/deploy/crds/gitea_v1alpha1_gitea_cr.yaml.

The Gitea Operator understands the following settings under it's *spec* setting:

* postgresqlVolumeSize: The size of the Persistent Volume to be created for the PostgreSQL database (e.g. 4Gi)
* giteaVolumeSize: The size of the Persistent Volume to be created for the Gitea database (e.g. 4Gi)
* giteaSsl: Weather the created route should be a HTTP (false) or HTTPS (true) route.

.Example
[source,texinfo]
----
apiVersion: gitea.opentlc.com/v1alpha1
kind: Gitea
metadata:
  name: gitea-server
spec:
  postgresqlVolumeSize: 4Gi
  giteaVolumeSize: 4Gi
  giteaSsl: True
----

. Write the definition to a file (e.g. gitea-server.yaml) and then create the Gitea instance:
+
[source,sh]
----
oc create -f ./gitea-server.yaml
----

. The operator will first create the PostgreSQL database, wait until it is up and running and then create the Gitea Server.
. Validate that both pods (postgresql and gitea) are running before proceeding.
. You can validate the existence of your Gitea Server by querying for gitea objects:
+
[source,sh]
----
oc get gitea
----

. Get the Route for the Gitea Server (the PostgreSQL database is not accessible outside of the project):
+
[source,sh]
----
oc get route
----

. Use the hostname returned in your Web Browser to open the Gitea UI.

== Deleting a Gitea Server

Deleting a gitea server and its associated resources is as simple as deleting the gitea object. If you created a gitea server called `gitea-server` as in the example above it suffices to run the delete command on that resource:

[source,sh]
----
oc delete gitea gitea-server
----

The Operator adds ownerReference fields to all created objects - which means that deleting the Gitea object also deletes all objects that have been created by the Operator.

== Uninstalling the Gitea Operator

In case you wish to uninstall the Gitea Operator make sure that there are no more Gitea instances running. Once all Gitea instances have been deleted simply delete the project the operator is running in.

[source,sh]
----
oc delete project gitea
----

Then as *cluster-admin* delete the ClusterRole and Custom Resource:

[source,sh]
----
oc delete clusterrole gitea-admin-rules
oc delete crd gitea.gpte.opentlc.com
----
