# permissions for end users to edit giteas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitea-editor-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - giteas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - giteas/status
  verbs:
  - get
