apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: giteas.gpte.redhat.com
spec:
  group: gpte.redhat.com
  names:
    kind: Gitea
    listKind: GiteaList
    plural: giteas
    singular: gitea
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
