apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitea.gpte.opentlc.com
spec:
  group: gpte.opentlc.com
  names:
    kind: Gitea
    listKind: GiteaList
    plural: gitea
    singular: gitea
  scope: Namespaced
  version: v1alpha1
