apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../crd
- ../../rbac
- ../../manager

namespace: gitea-operator-test
namePrefix: gitea-operator-

images:
- name: testing
  newName: testing-operator

patchesStrategicMerge:
- ../manager_image.yaml
- ../debug_logs_patch.yaml
