kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitea-operator
subjects:
- kind: ServiceAccount
  name: gitea-operator
  namespace: REPLACE_ME
roleRef:
  kind: ClusterRole
  name: gitea-operator
  apiGroup: rbac.authorization.k8s.io
