apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitea-operator
  template:
    metadata:
      labels:
        name: gitea-operator
    spec:
      serviceAccountName: gitea-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: quay.io/wkulhanek/gitea-operator/v0.9.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: quay.io/wkulhanek/gitea-operator/v0.9.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gitea-operator"
      volumes:
        - name: runner
          emptyDir: {}
