---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Install nginx Ingress onto kind
    command: >
      helm install kind-ingress ingress-nginx/ingress-nginx
      --set controller.service.type=NodePort
      --set controller.service.nodePorts.http=30080
