apiVersion: redhatgov.io/v1alpha1
kind: Gitea
metadata:
  name: gitea-sample
spec:
  postgresql:
    volumeSize: 1Gi
    image:
      src: postgres
      tag: '10'
  gitea:
    expose:
      ssl: true                           # There is currently no way to specify an alternate certificate
      uri: gitea-sample.example.com   # You can leave this field out on OpenShift to get the default
      kind: Ingress                       # This can be of kind Route on OpenShift (the default)
    image:
      src: quay.io/redhatgov/gitea
      tag: latest
      pullPolicy: Always
    volumeSize: 1Gi
  persistent: true
