---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create Namespace
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'

    - name: Create alternate namespace
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}-alt'

    - import_tasks: kustomize.yml
      vars:
        state: present
