---
- name: Build kustomize testing overlay
  # load-restrictor must be set to none so we can load patch files from the default overlay
  command: '{{ kustomize }} build  --load-restrictor LoadRestrictionsNone .'
  args:
    chdir: '{{ config_dir }}/testing/{{ scope|default("cluster") }}_scope'
  register: resources
  changed_when: false

- name: Set resources to {{ state }}
  community.kubernetes.k8s:
    definition: '{{ item }}'
    state: '{{ state }}'
    wait: yes
  loop: '{{ resources.stdout | from_yaml_all | list }}'
