---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.kubernetes

  tasks:
    - name: Unset pull policy
      command: '{{ kustomize }} edit remove patch pull_policy/{{ operator_pull_policy }}.yaml'
      args:
        chdir: '{{ config_dir }}/testing/{{ scope|default("cluster") }}_scope'
