---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
platforms:
  - name: cluster
    groups:
      - k8s
provisioner:
  name: ansible
  playbooks:
    create: ../kind-cluster/create.yml
    prepare: ../default/prepare.yml
    converge: ../kind-cluster/converge.yml
    verify: ../default/verify.yml
    destroy: ../kind-cluster/destroy.yml
  lint: |
    set -e
    ansible-lint
  inventory:
    group_vars:
      all:
        namespace: ${TEST_OPERATOR_NAMESPACE:-osdk-test}
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        config_dir: ${MOLECULE_PROJECT_DIRECTORY}/config
        samples_dir: ${MOLECULE_PROJECT_DIRECTORY}/config/samples
        project_dir: ${MOLECULE_PROJECT_DIRECTORY}
        operator_image: testing-operator
        operator_pull_policy: "Never"
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        kustomize: ${KUSTOMIZE_PATH:-kustomize}
        scope: namespace
  env:
    K8S_AUTH_KUBECONFIG: ${KUBECONFIG:-$HOME/.kube/config}
    KUBECONFIG: ${KUBECONFIG:-$HOME/.kube/config}
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
