---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: giteausers.redhatgov.io
spec:
  group: redhatgov.io
  names:
    kind: GiteaUser
    listKind: GiteaUserList
    plural: giteausers
    singular: giteauser
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: GiteaUser is the Schema for Gitea users
        properties:
          apiVersion:
            description: |
              APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |
              Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info:
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the user information to add to the local Gitea authorization list
            properties:
              user:
                description: Keycloak User REST object.
                properties:
                  username:
                    description: User Name.
                    type: string
                  password:
                    description: Password.
                    type: string
                  firstName:
                    description: First Name.
                    type: string
                  lastName:
                    description: Last Name.
                    type: string
                  email:
                    description: Email.
                    type: string
                required:
                - username
                - password
                type: object
            required:
            - user
            type: object
        type: object
